version: 2.1

jobs:
  build:
    docker:
        - image: python:3.8-buster

    steps:
        - checkout
        - run:
              name: Install poetry
              command: |
                curl -sSL https://install.python-poetry.org | python3 - --version 1.4.1
        - run:
            name: Add poetry to path
            command: |
              echo 'export PATH=${HOME}/.local/bin:${PATH}' >> $BASH_ENV

        - run:
            name: Install packages
            command: |
                poetry config virtualenvs.create false && poetry install --no-ansi
        - run:
            name: Verify linting & formatting
            command: |
                poe verify
        - run:
            name: Run tests
            command: |
                pytest .
        - store_test_results:
            path: reports